part of 'ffmpeg_stream_engine.dart';

List<String> _buildFfmpegArguments({
  required int videoPort,
  required int audioPort,
  required int width,
  required int height,
  required String pixelFormat,
  required String videoEncoder,
  required String ingestionUrl,
  bool forceHardwareEncoding = false,
  String? outputPath,
  StreamOutputResolution outputResolution = StreamOutputResolution.original,
  int videoBitrate = 4500,
  int frameRate = 30,
}) => [
  '-hide_banner',
  '-loglevel',
  'warning',
  // The camera's advertised rate is often nominal (for example, "30 fps"
  // hardware commonly delivers 30000/1001). Timestamp video from its arrival
  // clock so that this small difference cannot accumulate into long-term
  // drift. The video filter resets the epoch-based timestamps to zero.
  '-use_wallclock_as_timestamps',
  '1',
  '-f',
  'rawvideo',
  '-pixel_format',
  pixelFormat,
  '-video_size',
  '${width}x$height',
  '-framerate',
  '$frameRate',
  '-i',
  'tcp://127.0.0.1:$videoPort',
  '-f',
  's16le',
  '-ar',
  '48000',
  '-ac',
  '1',
  '-i',
  'tcp://127.0.0.1:$audioPort',
  '-map',
  '0:v:0',
  '-map',
  '1:a:0',
  '-vf',
  [
    'setpts=PTS-STARTPTS',
    // Match the fill-style camera preview and YouTube's 16:9 player by
    // center-cropping non-widescreen sources instead of letterboxing them.
    'crop=trunc(min(iw\\,ih*16/9)/2)*2:'
        'trunc(min(ih\\,iw*9/16)/2)*2',
    if (outputResolution case StreamOutputResolution(
      width: final width?,
      height: final height?,
    ))
      'scale=$width:$height',
    'setsar=1',
  ].join(','),
  '-fps_mode',
  'cfr',
  '-r',
  '$frameRate',
  '-c:v',
  videoEncoder,
  if (videoEncoder == 'h264_mf') ...[
    '-scenario',
    'live_streaming',
    if (forceHardwareEncoding) ...['-hw_encoding', '1'],
  ],
  if (videoEncoder == 'h264_nvenc') ...['-preset', 'p1', '-tune', 'll'],
  if (videoEncoder == 'h264_amf') ...[
    '-usage',
    'lowlatency',
    '-quality',
    'speed',
  ],
  if (videoEncoder == 'h264_qsv') ...['-preset', 'veryfast'],
  if (videoEncoder == 'h264_videotoolbox') ...[
    '-realtime',
    '1',
    '-allow_sw',
    '1',
  ],
  if (videoEncoder == 'libx264') ...[
    '-preset',
    'ultrafast',
    '-tune',
    'zerolatency',
  ],
  '-b:v',
  '${videoBitrate}k',
  '-maxrate',
  '${videoBitrate}k',
  '-bufsize',
  '${videoBitrate * 2}k',
  '-g',
  '${frameRate * 2}',
  '-keyint_min',
  '${frameRate * 2}',
  '-pix_fmt',
  'yuv420p',
  '-c:a',
  'aac',
  '-b:a',
  '128k',
  '-ar',
  '48000',
  '-ac',
  '2',
  '-f',
  'tee',
  '[f=flv:flvflags=no_duration_filesize:onfail=abort]$ingestionUrl'
      '${outputPath == null ? '' : '|[f=mp4:movflags=+faststart:onfail=ignore]$outputPath'}',
];
